#                                                                        #
# Default routes configuration for the Neos.Setup package                #
#                                                                        #

# While the setup is active on "setup/index", the URI "setup" is directly handled
# by the request handler to display a first screen and a loading indicator.
-
  name: 'Setup'
  uriPattern: 'setup/index'
  defaults:
    '@package':    'Neos.Setup'
    '@controller': 'Setup'
    '@action':     'index'
    '@format':     'html'
  appendExceedingArguments: true

-
  name: 'Login'
  uriPattern: 'setup/login(/{@action})'
  defaults:
    '@package':    'Neos.Setup'
    '@controller': 'Login'
    '@action':     'login'
    '@format':     'html'
  appendExceedingArguments: true